// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umrjdgvbsfkwxwlnelcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtcmpkZ3Zic2Zrd3h3bG5lbGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjQzNTQsImV4cCI6MjA2NjI0MDM1NH0.Vh1LClyj2YavKGz-59CPKEai-EmsRGZGLrL6-D618Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);